apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      service: udagram-api-feed
  replicas: 3
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - image: sha3baan/udagram-api-feed:v3
        name: udagram-api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: envsecret
          - configMapRef:
              name: envconfigmap


