apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      service: udagram-api-feed
  replicas: 3
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - image: sha3baan/udagram-api-feed:v3
        name: udagram-api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m  
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-secret
      volumes:
        - name: aws-secret
          configMap:
            name: aws-secret


