name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      run:
        docker login -u $DOCKER_USER -p $DOCKERHUB_TOKEN
    - name: Build and push to udagram-api-feed to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./udagram-api-feed
        push: true
        tags: sha3baan/udagram-api-feed:v3
    - name: Build and push to udagram-api-user to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./udagram-api-user
        push: true
        tags: sha3baan/udagram-api-user:v3
    - name: Build and push to udagram-frontend to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./udagram-frontend
        push: true
        tags: sha3baan/udagram-frontend:v4
    - name: Build and push to reverseproxy to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./udagram-reverseproxy
        push: true
        tags: sha3baan/udagram-reverseproxy:v3

